name: Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install build essentials
        run: apt-get update && apt-get install -y build-essential

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pygments bs4 lxml git+https://github.com/capjamesg/aurora
          cd docs
      - name: Build main site
        env:  
          SITE_ENV: ${{ secrets.SITE_ENV }}  
        run: |
          cd docs
          aurora build
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr
          path: "docs/_site/*"
          remote_path: ${{ secrets.PATH }}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USERNAME }}
          remote_key: ${{ secrets.KEY }}
