name: Publish documentation

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Install GCC and Git
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build essentials
        run: sudo apt-get install -y build-essential
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip aurora-ssg
          python3 -m pip install --upgrade pip pygments bs4 lxml
          pip3 install -e .
          cd docs
      - name: Build main site
        env:  
          SITE_ENV: ${{ secrets.SITE_ENV }}  
        run: |
          cd docs
          aurora build
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr
          path: "docs/_site/*"
          remote_path: ${{ secrets.PATH }}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USERNAME }}
          remote_key: ${{ secrets.KEY }}
